title: The Real Sweat Equity Podcast
description: Documentation and episode flows for The Real Sweat Equity Podcast
baseurl: "/real-sweat-equity-podcast-docs"
url: "https://rohanshar.github.io"

# GitHub Pages settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-relative-links

# Enable relative links
relative_links:
  enabled: true
  collections: true